# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/russell/ultrasound/fpga/us/us.srcs/sources_1/bd/bd/ip/bd_ila_0_0/bd_ila_0_0.xci
# IP: The module: 'bd_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_ila_0_0/bd_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/russell/ultrasound/fpga/us/us.srcs/sources_1/bd/bd/ip/bd_ila_0_0/bd_ila_0_0.xci
# IP: The module: 'bd_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_ila_0_0/bd_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
