# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins.xdc

# Block Designs: bd/bd/bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd || ORIG_REF_NAME==bd} -quiet] -quiet

# IP: bd/bd/ip/bd_xxv_ethernet_0_0/bd_xxv_ethernet_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_xxv_ethernet_0_0 || ORIG_REF_NAME==bd_xxv_ethernet_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_jesd204_phy_0_0/bd_jesd204_phy_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_jesd204_phy_0_0 || ORIG_REF_NAME==bd_jesd204_phy_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_util_ds_buf_0_0/bd_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_util_ds_buf_0_0 || ORIG_REF_NAME==bd_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_util_ds_buf_1_1/bd_util_ds_buf_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_util_ds_buf_1_1 || ORIG_REF_NAME==bd_util_ds_buf_1_1} -quiet] -quiet

# IP: bd/bd/ip/bd_clk_wiz_0_0/bd_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_clk_wiz_0_0 || ORIG_REF_NAME==bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_microblaze_riscv_0_0/bd_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_microblaze_riscv_0_0 || ORIG_REF_NAME==bd_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_dlmb_v10_0/bd_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dlmb_v10_0 || ORIG_REF_NAME==bd_dlmb_v10_0} -quiet] -quiet

# IP: bd/bd/ip/bd_ilmb_v10_0/bd_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ilmb_v10_0 || ORIG_REF_NAME==bd_ilmb_v10_0} -quiet] -quiet

# IP: bd/bd/ip/bd_dlmb_bram_if_cntlr_0/bd_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==bd_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bd/ip/bd_ilmb_bram_if_cntlr_0/bd_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==bd_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bd/ip/bd_lmb_bram_0/bd_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_lmb_bram_0 || ORIG_REF_NAME==bd_lmb_bram_0} -quiet] -quiet

# IP: bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_microblaze_riscv_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_microblaze_riscv_0_axi_periph_0 || ORIG_REF_NAME==bd_microblaze_riscv_0_axi_periph_0} -quiet] -quiet

# IP: bd/bd/ip/bd_microblaze_riscv_0_axi_intc_0/bd_microblaze_riscv_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_microblaze_riscv_0_axi_intc_0 || ORIG_REF_NAME==bd_microblaze_riscv_0_axi_intc_0} -quiet] -quiet

# IP: bd/bd/ip/bd_mdm_1_0/bd_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mdm_1_0 || ORIG_REF_NAME==bd_mdm_1_0} -quiet] -quiet

# IP: bd/bd/ip/bd_rst_sysclk_wiz_25M_0/bd_rst_sysclk_wiz_25M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_rst_sysclk_wiz_25M_0 || ORIG_REF_NAME==bd_rst_sysclk_wiz_25M_0} -quiet] -quiet

# IP: bd/bd/ip/bd_vio_0_0/bd_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_vio_0_0 || ORIG_REF_NAME==bd_vio_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_vio_0_1/bd_vio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_vio_0_1 || ORIG_REF_NAME==bd_vio_0_1} -quiet] -quiet

# IP: bd/bd/ip/bd_vio_0_2/bd_vio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_vio_0_2 || ORIG_REF_NAME==bd_vio_0_2} -quiet] -quiet

# IP: bd/bd/ip/bd_in_system_ibert_0_0/bd_in_system_ibert_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_in_system_ibert_0_0 || ORIG_REF_NAME==bd_in_system_ibert_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_c_counter_binary_0_0/bd_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c_counter_binary_0_0 || ORIG_REF_NAME==bd_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_c_counter_binary_1_0/bd_c_counter_binary_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c_counter_binary_1_0 || ORIG_REF_NAME==bd_c_counter_binary_1_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_iic_0_0/bd_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_iic_0_0 || ORIG_REF_NAME==bd_axi_iic_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_net_wrapper_0_0/bd_net_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_net_wrapper_0_0 || ORIG_REF_NAME==bd_net_wrapper_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_gpio_0_0/bd_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_gpio_0_0 || ORIG_REF_NAME==bd_axi_gpio_0_0} -quiet] -quiet

# XDC: /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/bd_ooc.xdc
