# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/russell/ultrasound/fpga/us/us.runs/synth_1/us_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param power.BramSDPPropagationFix 1
set_param power.enableLutRouteBelPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param tcl.collectionResultDisplayLimit 0
set_param physdb.placeDBImplUsesPlaceStorage 0
set_param bd.open.in_stealth_mode 1
set_param xicom.use_bs_reader 1
set_param general.usePosixSpawnForFork 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcau15p-ffvb676-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/russell/ultrasound/fpga/us/us.cache/wt [current_project]
set_property parent.project_path /home/russell/ultrasound/fpga/us/us.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/russell/ultrasound/fpga/us/us.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv /home/russell/ultrasound/fpga/us/us.srcs/sources_1/new/us_top.sv
read_verilog -library xil_defaultlib /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/hdl/bd_wrapper.v
add_files /home/russell/ultrasound/fpga/us/us.srcs/sources_1/bd/bd/bd.bd
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_xxv_ethernet_0_0/ip_1/synth/bd_xxv_ethernet_0_0_gt_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_xxv_ethernet_0_0/ip_1/synth/bd_xxv_ethernet_0_0_gt_1.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_xxv_ethernet_0_0/ip_0/synth/bd_xxv_ethernet_0_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_xxv_ethernet_0_0/ip_0/synth/bd_xxv_ethernet_0_0_gt.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_xxv_ethernet_0_0/synth/bd_xxv_ethernet_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_xxv_ethernet_0_0/synth/bd_xxv_ethernet_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_xxv_ethernet_0_0/synth/bd_xxv_ethernet_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_jesd204_phy_0_0/ip_0/synth/bd_jesd204_phy_0_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_jesd204_phy_0_0/ip_0/synth/bd_jesd204_phy_0_0_gt.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_jesd204_phy_0_0/synth/bd_jesd204_phy_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_jesd204_phy_0_0/synth/bd_jesd204_phy_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_jesd204_phy_0_0/synth/bd_jesd204_phy_0_0_clock_group.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_jesd204_phy_0_0/synth/bd_jesd204_phy_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_util_ds_buf_0_0/bd_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_util_ds_buf_0_0/bd_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_util_ds_buf_1_1/bd_util_ds_buf_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_util_ds_buf_1_1/bd_util_ds_buf_1_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_clk_wiz_0_0/bd_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_clk_wiz_0_0/bd_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_clk_wiz_0_0/bd_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_0/bd_microblaze_riscv_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_0/bd_microblaze_riscv_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_0/bd_microblaze_riscv_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_dlmb_v10_0/bd_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_ilmb_v10_0/bd_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_dlmb_bram_if_cntlr_0/bd_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_ilmb_bram_if_cntlr_0/bd_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_lmb_bram_0/bd_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_1/bd_f06c_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_2/bd_f06c_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_3/bd_f06c_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_4/bd_f06c_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_5/bd_f06c_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_6/bd_f06c_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_7/bd_f06c_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_8/bd_f06c_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_9/bd_f06c_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_10/bd_f06c_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_11/bd_f06c_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_12/bd_f06c_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_13/bd_f06c_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_14/bd_f06c_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_15/bd_f06c_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_16/bd_f06c_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_20/bd_f06c_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_21/bd_f06c_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_22/bd_f06c_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_23/bd_f06c_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_24/bd_f06c_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_25/bd_f06c_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_26/bd_f06c_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_27/bd_f06c_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_28/bd_f06c_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_29/bd_f06c_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_30/bd_f06c_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_31/bd_f06c_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_33/bd_f06c_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_34/bd_f06c_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_35/bd_f06c_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_36/bd_f06c_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_37/bd_f06c_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_38/bd_f06c_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_40/bd_f06c_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_41/bd_f06c_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_42/bd_f06c_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_43/bd_f06c_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_44/bd_f06c_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_45/bd_f06c_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_periph_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_intc_0/bd_microblaze_riscv_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_intc_0/bd_microblaze_riscv_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_axi_intc_0/bd_microblaze_riscv_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_mdm_1_0/bd_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_mdm_1_0/bd_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_mdm_1_0/bd_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_rst_sysclk_wiz_25M_0/bd_rst_sysclk_wiz_25M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_rst_sysclk_wiz_25M_0/bd_rst_sysclk_wiz_25M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_vio_0_0/bd_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_vio_0_0/bd_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_vio_0_1/bd_vio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_vio_0_1/bd_vio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_vio_0_2/bd_vio_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_vio_0_2/bd_vio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_c_counter_binary_0_0/bd_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_c_counter_binary_1_0/bd_c_counter_binary_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_axi_iic_0_0/bd_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_axi_iic_0_0/bd_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_axi_gpio_0_0/bd_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_axi_gpio_0_0/bd_axi_gpio_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_ila_0_0/bd_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/bd_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/russell/ultrasound/fpga/us/us.gen/sources_1/bd/bd/ip/bd_microblaze_riscv_0_0/data/riscv_bootloop.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/russell/ultrasound/fpga/us/us.srcs/constrs_1/new/pins.xdc
set_property used_in_implementation false [get_files /home/russell/ultrasound/fpga/us/us.srcs/constrs_1/new/pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/russell/ultrasound/fpga/us/us.srcs/utils_1/imports/synth_1/us_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top us_top -part xcau15p-ffvb676-2-i
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef us_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file us_top_utilization_synth.rpt -pb us_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
