set_property PACKAGE_PIN K9 [get_ports {pulser0_neg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulser0_neg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulser0_neg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulser0_neg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulser0_neg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulser0_pos[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulser0_pos[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulser0_pos[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulser0_pos[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulser1_neg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulser1_neg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulser1_neg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulser1_neg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulser1_pos[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulser1_pos[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulser1_pos[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulser1_pos[0]}]
set_property PACKAGE_PIN K10 [get_ports {pulser0_pos[0]}]
set_property PACKAGE_PIN J10 [get_ports pulser0_optn]
set_property PACKAGE_PIN H9 [get_ports {pulser1_neg[0]}]
set_property PACKAGE_PIN J9 [get_ports {pulser1_pos[0]}]
set_property PACKAGE_PIN J11 [get_ports mux_clr]
set_property PACKAGE_PIN F9 [get_ports pulser1_optn]
set_property PACKAGE_PIN F10 [get_ports mux_din]
set_property PACKAGE_PIN D10 [get_ports clk_sda]
set_property IOSTANDARD LVCMOS33 [get_ports clk_scl]
set_property IOSTANDARD LVCMOS33 [get_ports mux_clk]
set_property IOSTANDARD LVCMOS33 [get_ports mux_clr]
set_property IOSTANDARD LVCMOS33 [get_ports mux_le]
set_property IOSTANDARD LVCMOS33 [get_ports pulser0_optn]
set_property IOSTANDARD LVCMOS33 [get_ports pulser1_optn]
set_property IOSTANDARD LVCMOS33 [get_ports mux_din]
set_property IOSTANDARD LVCMOS33 [get_ports clk_sda]
set_property PACKAGE_PIN AF13 [get_ports hvplus_scl]
set_property PACKAGE_PIN AE13 [get_ports hvplus_sda]
set_property IOSTANDARD LVCMOS33 [get_ports hvplus_sda]
set_property PACKAGE_PIN AE15 [get_ports hvminus_scl]
set_property IOSTANDARD LVCMOS33 [get_ports hvplus_scl]
set_property IOSTANDARD LVCMOS33 [get_ports hvminus_scl]
set_property IOSTANDARD LVCMOS33 [get_ports hvminus_sda]
set_property PACKAGE_PIN AD15 [get_ports hvminus_sda]
set_property PACKAGE_PIN AC14 [get_ports {pulser1_neg[3]}]
set_property PACKAGE_PIN AB16 [get_ports sfp_scl]
set_property PACKAGE_PIN AB15 [get_ports sfp_sda]
set_property IOSTANDARD LVCMOS33 [get_ports sfp_sda]
set_property IOSTANDARD LVCMOS33 [get_ports sfp_scl]
set_property PACKAGE_PIN AA15 [get_ports pulser_oen]
set_property IOSTANDARD LVCMOS33 [get_ports pulser_oen]
set_property PACKAGE_PIN Y15 [get_ports {pulser0_neg[1]}]
set_property PACKAGE_PIN AB14 [get_ports {pulser0_neg[3]}]
set_property PACKAGE_PIN AA14 [get_ports {pulser0_pos[3]}]
set_property PACKAGE_PIN Y16 [get_ports {pulser1_neg[1]}]
set_property PACKAGE_PIN W16 [get_ports {pulser1_pos[1]}]
set_property PACKAGE_PIN W15 [get_ports {pulser0_pos[1]}]
set_property PACKAGE_PIN W14 [get_ports pulser_clk]
set_property IOSTANDARD LVCMOS33 [get_ports pulser_clk]
set_property PACKAGE_PIN AA13 [get_ports {pulser1_neg[2]}]
set_property PACKAGE_PIN Y13 [get_ports {pulser1_pos[2]}]
set_property PACKAGE_PIN W13 [get_ports {pulser0_neg[2]}]
set_property PACKAGE_PIN W12 [get_ports {pulser0_pos[2]}]
set_property PACKAGE_PIN AC13 [get_ports {pulser1_pos[3]}]
set_property PACKAGE_PIN F13 [get_ports uart_rx]
set_property PACKAGE_PIN F14 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property PACKAGE_PIN AC19 [get_ports jesd_coreclkp]
set_property PACKAGE_PIN AD19 [get_ports jesd_coreclkn]
set_property PACKAGE_PIN AE16 [get_ports adc0_rst]
set_property PACKAGE_PIN AD16 [get_ports adc0_sclk]
set_property PACKAGE_PIN AA19 [get_ports adc0_miso]
set_property IOSTANDARD LVCMOS18 [get_ports adc0_rst]
set_property IOSTANDARD LVCMOS18 [get_ports adc0_miso]
set_property IOSTANDARD LVCMOS18 [get_ports adc0_mosi]
set_property IOSTANDARD LVCMOS18 [get_ports adc0_cs]
set_property PACKAGE_PIN AA17 [get_ports adc0_cs]
set_property PACKAGE_PIN Y17 [get_ports adc0_mosi]
set_property IOSTANDARD LVCMOS18 [get_ports adc0_sclk]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_rst]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_sclk]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_mosi]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_miso]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_cs]
set_property PACKAGE_PIN W26 [get_ports adc1_sclk]
set_property PACKAGE_PIN V26 [get_ports adc1_mosi]
set_property PACKAGE_PIN U26 [get_ports adc1_rst]
set_property PACKAGE_PIN P26 [get_ports adc1_miso]
set_property PACKAGE_PIN P25 [get_ports adc1_cs]
set_property PACKAGE_PIN AB6 [get_ports eth_refclkn]
set_property PACKAGE_PIN AB7 [get_ports eth_refclkp]
set_property PACKAGE_PIN V6 [get_ports jesd_refclkn]
set_property PACKAGE_PIN V7 [get_ports jesd_refclkp]
set_property LOC GTHE4_CHANNEL_X0Y4 [get_cells {bd/bd_i/jesd204_phy_0/inst/jesd204_phy_block_i/bd_jesd204_phy_0_0_gt_i/inst/gen_gtwizard_gthe4_top.bd_jesd204_phy_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[1].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST}]
set_property PACKAGE_PIN Y2 [get_ports adc0_ddp]
set_property PACKAGE_PIN Y1 [get_ports adc0_ddn]
set_property LOC GTHE4_CHANNEL_X0Y5 [get_cells {bd/bd_i/jesd204_phy_0/inst/jesd204_phy_block_i/bd_jesd204_phy_0_0_gt_i/inst/gen_gtwizard_gthe4_top.bd_jesd204_phy_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[1].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[1].GTHE4_CHANNEL_PRIM_INST}]
set_property PACKAGE_PIN V2 [get_ports adc0_dap]
set_property PACKAGE_PIN V1 [get_ports adc0_dan]
set_property LOC GTHE4_CHANNEL_X0Y6 [get_cells {bd/bd_i/jesd204_phy_0/inst/jesd204_phy_block_i/bd_jesd204_phy_0_0_gt_i/inst/gen_gtwizard_gthe4_top.bd_jesd204_phy_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[1].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[2].GTHE4_CHANNEL_PRIM_INST}]
set_property PACKAGE_PIN T2 [get_ports adc1_ddp]
set_property PACKAGE_PIN T1 [get_ports adc1_ddn]
set_property LOC GTHE4_CHANNEL_X0Y7 [get_cells {bd/bd_i/jesd204_phy_0/inst/jesd204_phy_block_i/bd_jesd204_phy_0_0_gt_i/inst/gen_gtwizard_gthe4_top.bd_jesd204_phy_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[1].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[3].GTHE4_CHANNEL_PRIM_INST}]
set_property PACKAGE_PIN P2 [get_ports adc1_dap]
set_property PACKAGE_PIN P1 [get_ports adc1_dan]

set_property PACKAGE_PIN T24 [get_ports osc200mhz_p]
set_property IOSTANDARD LVDS [get_ports osc200mhz_p]
set_property IOSTANDARD LVDS [get_ports jesd_coreclkp]

set_property PACKAGE_PIN U19 [get_ports adc0_syncp]
set_property PACKAGE_PIN U21 [get_ports adc1_syncp]

set_property IOSTANDARD LVDS [get_ports adc0_syncp]
set_property IOSTANDARD LVDS [get_ports adc0_syncn]
set_property IOSTANDARD LVDS [get_ports adc1_syncp]

create_clock -period 20.000 -name jesd_coreclk -waveform {0.000 10.000} [get_ports jesd_coreclkp]
create_clock -period 10.000 -name jesd_refclk -waveform {0.000 5.000} [get_ports jesd_refclkp]

set_property PACKAGE_PIN G11 [get_ports ramp_scl]
set_property PACKAGE_PIN H11 [get_ports ramp_sda]
set_property IOSTANDARD LVCMOS33 [get_ports ramp_scl]
set_property PACKAGE_PIN G9 [get_ports mux_aux0]
set_property IOSTANDARD LVCMOS33 [get_ports ramp_sda]
set_property PACKAGE_PIN G10 [get_ports mux_aux2]
set_property IOSTANDARD LVCMOS33 [get_ports mux_aux0]
set_property IOSTANDARD LVCMOS33 [get_ports mux_aux2]
set_property PACKAGE_PIN D11 [get_ports clk_scl]
set_property PACKAGE_PIN C9 [get_ports mux_aux1]
set_property IOSTANDARD LVCMOS33 [get_ports mux_aux1]
set_property PACKAGE_PIN D9 [get_ports mux_le]
set_property PACKAGE_PIN A10 [get_ports ramp_rst]
set_property IOSTANDARD LVCMOS33 [get_ports ramp_rst]
set_property PACKAGE_PIN B10 [get_ports mux_clk]

set_property PACKAGE_PIN A9 [get_ports {usrled[1]}]
set_property PACKAGE_PIN B9 [get_ports {usrled[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {usrled[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {usrled[0]}]
set_property PACKAGE_PIN AF15 [get_ports {test[4]}]
set_property PACKAGE_PIN AF14 [get_ports {test[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test[5]}]
set_property PACKAGE_PIN AD13 [get_ports sfp_mod_abs]
set_property IOSTANDARD LVCMOS33 [get_ports sfp_mod_abs]
set_property PACKAGE_PIN W20 [get_ports {test[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[0]}]
set_property PACKAGE_PIN Y23 [get_ports {test[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[2]}]
set_property PACKAGE_PIN AA24 [get_ports {test[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[3]}]
set_property PACKAGE_PIN P20 [get_ports {test[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[1]}]

set_property PACKAGE_PIN AD14 [get_ports {test[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test[6]}]

set_property LOC GTHE4_CHANNEL_X0Y1 [get_cells {bd/bd_i/xxv_ethernet_0/inst/i_bd_xxv_ethernet_0_0_gt_1/inst/gen_gtwizard_gthe4_top.bd_xxv_ethernet_0_0_gt_1_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[0].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST}]
set_property PACKAGE_PIN AE9 [get_ports sfp_txp]


set_property MARK_DEBUG true [get_nets {bd/bd_i/jesd_to_axi4s_0/inst/skip[5]}]
set_property MARK_DEBUG true [get_nets {bd/bd_i/jesd_to_axi4s_0/inst/skip[0]}]
set_property MARK_DEBUG true [get_nets {bd/bd_i/jesd_to_axi4s_0/inst/last_ctr[3]}]
set_property MARK_DEBUG true [get_nets {bd/bd_i/jesd_to_axi4s_0/inst/last_ctr[4]}]
set_property MARK_DEBUG true [get_nets {bd/bd_i/jesd_to_axi4s_0/inst/last_ctr[7]}]
set_property MARK_DEBUG true [get_nets {bd/bd_i/jesd_to_axi4s_0/inst/skip[1]}]
set_property MARK_DEBUG true [get_nets {bd/bd_i/jesd_to_axi4s_0/inst/skip[2]}]
set_property MARK_DEBUG true [get_nets {bd/bd_i/jesd_to_axi4s_0/inst/skip[3]}]
set_property MARK_DEBUG true [get_nets {bd/bd_i/jesd_to_axi4s_0/inst/skip[4]}]
set_property MARK_DEBUG true [get_nets {bd/bd_i/jesd_to_axi4s_0/inst/skip[6]}]
set_property MARK_DEBUG true [get_nets {bd/bd_i/jesd_to_axi4s_0/inst/skip[7]}]
set_property MARK_DEBUG true [get_nets {bd/bd_i/jesd_to_axi4s_0/inst/last_ctr[0]}]
set_property MARK_DEBUG true [get_nets {bd/bd_i/jesd_to_axi4s_0/inst/last_ctr[5]}]
set_property MARK_DEBUG true [get_nets {bd/bd_i/jesd_to_axi4s_0/inst/last_ctr[1]}]
set_property MARK_DEBUG true [get_nets {bd/bd_i/jesd_to_axi4s_0/inst/last_ctr[2]}]
set_property MARK_DEBUG true [get_nets {bd/bd_i/jesd_to_axi4s_0/inst/last_ctr[6]}]
set_property MARK_DEBUG true [get_nets bd/bd_i/jesd_to_axi4s_0/inst/rx_valid]
set_property MARK_DEBUG true [get_nets bd/bd_i/jesd_to_axi4s_0/inst/m_axis_tready]
set_property MARK_DEBUG true [get_nets bd/bd_i/jesd_to_axi4s_0/inst/m_axis_tlast]

set_property MARK_DEBUG true [get_nets {bd/bd_i/net_wrapper_0/inst/net_inst/udp_xfcp\\.hdr_ready}]
set_property MARK_DEBUG true [get_nets {bd/bd_i/net_wrapper_0/inst/net_inst/arb_inst/grant_encoded_next[0]}]
set_property MARK_DEBUG true [get_nets {bd/bd_i/net_wrapper_0/inst/net_inst/grant_encoded[0]}]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
#set_property BITSTREAM.CONFIG.PERSIST NO [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 51.0 [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullup [current_design]

#create_debug_core u_ila_0 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
#set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
#set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
#set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
#set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
#set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
#set_property port_width 1 [get_debug_ports u_ila_0/clk]
#connect_debug_port u_ila_0/clk [get_nets [list u_ila_0_gen_gtwiz_userclk_rx_main.bufg_gt_usrclk2_inst_0]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
#set_property port_width 8 [get_debug_ports u_ila_0/probe0]
#connect_debug_port u_ila_0/probe0 [get_nets [list {bd/bd_i/jesd_to_axi4s_0/inst/skip[0]} {bd/bd_i/jesd_to_axi4s_0/inst/skip[1]} {bd/bd_i/jesd_to_axi4s_0/inst/skip[2]} {bd/bd_i/jesd_to_axi4s_0/inst/skip[3]} {bd/bd_i/jesd_to_axi4s_0/inst/skip[4]} {bd/bd_i/jesd_to_axi4s_0/inst/skip[5]} {bd/bd_i/jesd_to_axi4s_0/inst/skip[6]} {bd/bd_i/jesd_to_axi4s_0/inst/skip[7]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
#set_property port_width 8 [get_debug_ports u_ila_0/probe1]
#connect_debug_port u_ila_0/probe1 [get_nets [list {bd/bd_i/jesd_to_axi4s_0/inst/last_ctr[0]} {bd/bd_i/jesd_to_axi4s_0/inst/last_ctr[1]} {bd/bd_i/jesd_to_axi4s_0/inst/last_ctr[2]} {bd/bd_i/jesd_to_axi4s_0/inst/last_ctr[3]} {bd/bd_i/jesd_to_axi4s_0/inst/last_ctr[4]} {bd/bd_i/jesd_to_axi4s_0/inst/last_ctr[5]} {bd/bd_i/jesd_to_axi4s_0/inst/last_ctr[6]} {bd/bd_i/jesd_to_axi4s_0/inst/last_ctr[7]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
#set_property port_width 1 [get_debug_ports u_ila_0/probe2]
#connect_debug_port u_ila_0/probe2 [get_nets [list {bd/bd_i/net_wrapper_0/inst/net_inst/arb_inst/grant_encoded_next[0]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
#set_property port_width 1 [get_debug_ports u_ila_0/probe3]
#connect_debug_port u_ila_0/probe3 [get_nets [list bd/bd_i/jesd_to_axi4s_0/inst/m_axis_tlast]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
#set_property port_width 1 [get_debug_ports u_ila_0/probe4]
#connect_debug_port u_ila_0/probe4 [get_nets [list bd/bd_i/jesd_to_axi4s_0/inst/m_axis_tready]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
#set_property port_width 1 [get_debug_ports u_ila_0/probe5]
#connect_debug_port u_ila_0/probe5 [get_nets [list bd/bd_i/jesd_to_axi4s_0/inst/rx_valid]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
#set_property port_width 1 [get_debug_ports u_ila_0/probe6]
#connect_debug_port u_ila_0/probe6 [get_nets [list bd/bd_i/net_wrapper_0/inst/s_data_tlast]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
#set_property port_width 1 [get_debug_ports u_ila_0/probe7]
#connect_debug_port u_ila_0/probe7 [get_nets [list bd/bd_i/net_wrapper_0/inst/s_data_tready]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
#set_property port_width 1 [get_debug_ports u_ila_0/probe8]
#connect_debug_port u_ila_0/probe8 [get_nets [list bd/bd_i/net_wrapper_0/inst/s_data_tvalid]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
#set_property port_width 1 [get_debug_ports u_ila_0/probe9]
#connect_debug_port u_ila_0/probe9 [get_nets [list {bd/bd_i/net_wrapper_0/inst/net_inst/udp_adc\\.hdr_valid}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
#set_property port_width 1 [get_debug_ports u_ila_0/probe10]
#connect_debug_port u_ila_0/probe10 [get_nets [list {bd/bd_i/net_wrapper_0/inst/net_inst/udp_xfcp\\.hdr_ready}]]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets clk]
